#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-MySQL
version:      0.02
version_from: lib/Crypt/MySQL.pm
installdirs:  site
requires:
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
